### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Cloud-Session#12]
After experiencing some server failures today, we found this in the catalina.out (Tomcat7) file while the server was shutting down for a restart. It may be of no concern since the app was shutting down when the errors occurred, but it also may be a clue as to the problems we've experienced with Cloud-Session freeze up in Feb '16 and now with the Production system.  This may (or may not) relate to the cause of [BlocklyProp Issue#139](https://github.com/parallaxinc/BlocklyProp/issues/139) and [Cloud-Compiler Issue#7](https://github.com/parallaxinc/Cloud-Compiler/issues/7).

Mar 09, 2016 7:42:30 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/cloudsession] created a ThreadLocal with key of type [java.lang.ThreadLocal] (va
lue [java.lang.ThreadLocal@15cf53d7]) and a value of type [org.jooq.impl.DefaultDSLContext] (value [DefaultCon
figuration [
        connected=true,
        transactional=false,
        dialect=MYSQL,
        data={},
        settings=
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <settings xmlns:ns2="http://www.jooq.org/xsd/jooq-runtime-3.6.0.xsd">
                    <ns2:renderSchema>true</ns2:renderSchema>
                    <ns2:renderMapping>
                        <ns2:schemata/>
                    </ns2:renderMapping>
                    <ns2:renderNameStyle>QUOTED</ns2:renderNameStyle>
                    <ns2:renderKeywordStyle>AS_IS</ns2:renderKeywordStyle>
                    <ns2:renderFormatted>false</ns2:renderFormatted>
                    <ns2:renderScalarSubqueriesForStoredFunctions>false</ns2:renderScalarSubqueriesForStoredFu
nctions>
                    <ns2:backslashEscaping>DEFAULT</ns2:backslashEscaping>
                    <ns2:paramType>INDEXED</ns2:paramType>
                    <ns2:statementType>PREPARED_STATEMENT</ns2:statementType>
                    <ns2:executeLogging>true</ns2:executeLogging>
                    <ns2:executeWithOptimisticLocking>false</ns2:executeWithOptimisticLocking>
                    <ns2:attachRecords>true</ns2:attachRecords>
                    <ns2:updatablePrimaryKeys>false</ns2:updatablePrimaryKeys>
                    <ns2:reflectionCaching>true</ns2:reflectionCaching>
                    <ns2:fetchWarnings>true</ns2:fetchWarnings>
                </settings>
]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to
 try and avoid a probable memory leak.

Mar 09, 2016 7:42:30 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/cloudsession] created a ThreadLocal with key of type [com.codahale.metrics.Threa
dLocalRandom$1] (value [com.codahale.metrics.ThreadLocalRandom$1@62afbd37]) and a value of type [com.codahale.
metrics.ThreadLocalRandom] (value [com.codahale.metrics.ThreadLocalRandom@7faf987e]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

Mar 09, 2016 7:42:30 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/cloudsession] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@6144b9af]) and a value of type [org.jooq.impl.DefaultConnectionProvider] (value [org.jooq.impl.DefaultConnectionProvider@66fac20c]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

Mar 09, 2016 7:42:30 PM org.apache.catalina.loader.WebappClassLoader checkThreadLocalMapForLeaks
SEVERE: The web application [/cloudsession] created a ThreadLocal with key of type [com.codahale.metrics.ThreadLocalRandom$1] (value [com.codahale.metrics.ThreadLocalRandom$1@62afbd37]) and a value of type [com.codahale.metrics.ThreadLocalRandom] (value [com.codahale.metrics.ThreadLocalRandom@58d9d6a5]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by zfi** [comment]
This may no longer be an issue with the new python code base. Does anyone object to closing this issue?

**Comment by PropGit** [comment]
@zfi - I do not object to closing this, and will do so now.  Thanks!
