### ISSUE TITLE
Confused about the email templates.

### ISSUE THREAD

**Issue by tinywinds** [parallaxinc/Cloud-Session#22]
Is there only four available placeholders ?

> The available placeholders are:
> {{email}} This will be replaced with the email address of the user
> {{locale}} This will be replaced with the locale of the user (will be the same as the name of the directory)
> {{screenname}} This will be replaced with the screenname of the user
> {{token}} This will be replaced with the token the user has to use for the specific operation

How can I configure the mail object?   Is there a complete template for demonstration ?

**Comment by zfi** [comment]
The existing templates are all we need for our purposes. If you want to expand this feature, take a look at the app/Email/services.py file. This is where the the template file is parsed and married with the data declared within the template file. New placeholders can be defined in this file.
